default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: railscms
  password: root
  socket: /tmp/mysql.sock 

development:
  <<: *default
  database: railscms_development
test:
  <<: *default
  database: railscms_test
